### ISSUE TITLE
Issue with null incidentKey

### ISSUE THREAD

**Issue by wyardley** [alexanderlz/jenkins-pagerduty-plugin#19]
I'm seeing an issue that seems as if it could be related to https://github.com/jenkinsci/pagerduty-plugin/commit/71c92846b6d1d487858d445bd3a1dd3a68bfb979 ? 
 
first, a build seems to have some kind of transient problem hitting the API:
```
Triggering PagerDuty Notification
Triggering pagerDuty with serviceKey  XXXXXXXXXXXXX 
Triggering pagerDuty with incidentKey null
Triggering pagerDuty with incDescription My Description
PagerDuty returned NULL. check network or PD settings!Finished: FAILURE
```

The following run gives
```

Triggering PagerDuty Notification
Triggering pagerDuty with serviceKey  XXXXXXXXXXXXX 
Triggering pagerDuty with incidentKey null
Triggering pagerDuty with incDescription My Description
PagerDuty returned NULL. check network or PD settings!Finished: ABORTED
```
and then subsequent runs give:
```
Resolving incident
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: 'incidentKey' must not be blank. Was: ''
	at com.squareup.pagerduty.incidents.Util.checkArgument(Util.java:39)
	at com.squareup.pagerduty.incidents.Util.checkStringArgument(Util.java:26)
	at com.squareup.pagerduty.incidents.Resolution$Builder.<init>(Resolution.java:44)
	at org.jenkinsci.plugins.pagerduty.PagerDutyTrigger.resolveIncident(PagerDutyTrigger.java:221)
	at org.jenkinsci.plugins.pagerduty.PagerDutyTrigger.perform(PagerDutyTrigger.java:214)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'PagerDuty Incident Trigger' marked build as failure
```

If I set the incidentKey explicitly to empty or even remove that line from the .xml config, it still has a problem, however, setting the incidentKey explicitly to a random string and running the plugin, then resetting it back to null, seems to resolve the problem.

**Comment by wyardley** [comment]
If it helps, I had enabled the option to "Create alerts and incidents" (vs. just incidents)

**Comment by wyardley** [comment]
Even after creating incidents only, I get this after a failure. Clearing the incident within PD doesn't help (but the incidentKey is null in the config on the Jenkins side).

If I set the incident key to a random string, I get:
```
Resolving incident
Attempt to resolve the incident returned null - Incident may already be closed or may not exist.

Finished: SUCCESS
```

**Comment by alexanderlz** [comment]
Hi @wyardley, 
will give it a look in the upcoming day/two, thanks!

**Comment by wyardley** [comment]
@alexanderlz thanks in advance!

**Comment by wyardley** [comment]
@alexanderlz any update? Still having this happen with some frequency. Also wondering if you'll be switching to the v2 API (per #20).

**Comment by alexanderlz** [comment]
Hi @wyardley 
I couldn't reproduce, but this made me to create a gitter channel 
https://gitter.im/jenkinsci/pagerduty-plugin

let's get online there and you guide me how to reproduce the issue.

about v2 - yes, plan to migrate in the upcoming month

**Comment by alexanderlz** [comment]
resolved https://github.com/jenkinsci/pagerduty-plugin/commit/a8a9a582068ade0f91603228af4deb40e44f8b9c
